global using Carter;
global using EShop.BuildingBlocks.CQRS;
global using EShop.Catalog.Api.Exceptions;
global using EShop.Catalog.Api.Models;
global using Mapster;
global using Marten;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using FluentValidation;
