services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  eshop.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShop.Catalog.Api/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket: