services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  eshop.catalog.api:
    image: ${DOCKER_REGISTRY-}eshopcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/EShop.Catalog.Api/Dockerfile

  eshop.basket.api:
    image: ${DOCKER_REGISTRY-}eshopbasketapi
    build:
      context: .
      dockerfile: Services/Basket/EShop.Basket.Api/Dockerfile

  eshop.discount.grpc:
    image: ${DOCKER_REGISTRY-}eshopdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/EShop.Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  sqlserver_order:  
  rabbitmq_data: